# Generated by Django 5.2.14 on 2026-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administration',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
